### ISSUE TITLE
remove final lines and add a farewell message

### ISSUE THREAD

**Issue by badukaire** [annaaz8/equ2g#3]
At the end of the file there are many lines that should not be. These lines contain blanks and that [can cause errors in python](https://docs.python.org/2.0/ref/indentation.html).

Perhaps it is also a good idea to add a farewell message to the program.

https://github.com/annaaz8/equ2g/blob/07a2be4fb2acf1074ce86a8e4261a11026b06158/equ2g.py#L38

**Comment by annaaz8** [comment]
fixed
